language: scala
scala:
 - 2.13.3
 - 2.12.8
jdk: openjdk8
env:
 - WEBDRIVER_CHROME_DRIVER="/usr/lib/chromium-browser/chromedriver"
 - WEBDRIVER_GECKO_DRIVER="/usr/lib/geckodriver/geckodriver"
script:
 - sbt ++$TRAVIS_SCALA_VERSION test
 - sbt ++$TRAVIS_SCALA_VERSION inttest
dist: bionic
addons:
 chrome: stable
 firefox: latest
 apt:
  packages:
    - chromium-chromedriver
    - firefox-geckodriver
