language: scala
scala:
 - 2.13.0
 - 2.12.8
 - 2.11.12
jdk: openjdk8
env:
 - WEBDRIVER_CHROME_DRIVER="/usr/lib/chromium-browser/chromedriver"
script:
 - sbt ++$TRAVIS_SCALA_VERSION test
 - sbt ++$TRAVIS_SCALA_VERSION inttest
dist: bionic
addons:
 chrome: stable
 apt:
  packages:
    - chromium-chromedriver
